### ISSUE TITLE
dse-graph-frame

### ISSUE THREAD

**Issue by suhas-p-bharadwaj** [datastax/graph-examples#17]
Hi,

When I try to execute the sbt packge build, am getting the following error 
[error] Unable to find credentials for [Artifactory Realm @ repo.datastax.com].

Looks like its not able to connect to the datastax artifactory repos to download the dependencies. 

Am currently on sbt 0.13.11

Thanks!

**Comment by suhas-p-bharadwaj** [comment]
Upgrade to SBT worked !

**Comment by aditya-sridhar** [comment]
Which version of Sbt worked for this.
