### ISSUE TITLE
dse gremlin-console -i schema.groovy  giving Error

### ISSUE THREAD

**Issue by nithinbalantpm** [datastax/graph-examples#20]
I am using DSE5.1.0 when i use
dse gremlin-console -i schema.groovy
Error in ll.groovy at [2: system.graph("groovytest").ifNotExists().create()] - No such property: system for class: groovysh_evaluate

**Comment by spmallette** [comment]
This repository is for examples for DSE Graph, not really for general questions about usage. I saw an identical question posted on SO:

https://stackoverflow.com/q/49707133/1831717

You should get help for it there. Thanks.
